apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: m8loyhga8-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-b73aff0ede.viem.p3.openshiftapps.com/rhtap/rhtap-qe-dotnet-basic:3136f96c96be7719546f474f191f19aa4499ba36@sha256:50977ba4c0f6d570a71ad120dbfd087ae38442878bd6f5e4a90dd90fa9bd1542
          name: container-image
